function C = load_campagnola_matrices()
%LOAD_CAMPAGNOLA_MATRICES  Cell-type parameter matrices from Campagnola et al. 2022.
%
%   C = LOAD_CAMPAGNOLA_MATRICES() returns a struct of mouse cortical connectivity
%   and synapse parameters for 4 subclasses (Pyr, Pvalb, Sst, Vip), pooled across
%   layers, extracted from the Allen synaptic-physiology 'small' database.
%
%   Every matrix is 4x4 with rows = PREsynaptic type and cols = POSTsynaptic type,
%   ordered C.types = {'pyr','pvalb','sst','vip'}. Elements with fewer than 2
%   sampled pairs are NaN. Each per-connection metric has a matching sample-count
%   field <name>_n.
%
%   Fields (4x4 unless noted):
%     Connectivity : conn_prob, conn_prob_adj (distance-adjusted), n_probed, n_connected
%     Strength     : psp_amplitude (V), pulse_amp_90pct
%     STP          : stp_induction_50hz (>0 facilitating, <0 depressing),
%                    stp_recovery_250ms, variability_resting
%     Release model: ml_facilitation_amount, ml_facilitation_tau,
%                    ml_depression_amount, ml_depression_tau, ml_release_prob,
%                    ml_n_release_sites, ml_mini_amplitude
%     Kinetics     : latency, psc_rise_time, psc_decay_tau
%     Intrinsic (4x1, by cell type; SI units): sfa_adaptation_index (SFA),
%                    isi_adapt_ratio, tau [s], fi_slope [Hz/A], rheobase [A],
%                    input_resistance [Ohm]  (each with a matching _n)
%     types        : {'pyr','pvalb','sst','vip'}  (row/col order)
%
%   Reads the committed CSVs under src/connectivity/campagnola/ (the version-
%   controlled source of truth), generated by
%   scripts/aisynphys/extract_campagnola_matrices.py. See campagnola/PROVENANCE.md
%   for the DB version and query details. (A campagnola_matrices.mat is also written
%   by the extractor as a convenience but is gitignored and not required here.)
%
%   Example:
%     C = load_campagnola_matrices();
%     i = @(t) find(strcmp(C.types, t));
%     C.conn_prob_adj(i('pyr'), i('pvalb'))   % Pyr -> Pvalb adjusted connection prob

    this_dir = fileparts(mfilename('fullpath'));
    csv_dir  = fullfile(this_dir, 'campagnola', 'csv');
    if ~isfolder(csv_dir)
        error('load_campagnola_matrices:missing', ...
            ['Campagnola CSVs not found at:\n  %s\n' ...
             'Regenerate with: scripts/aisynphys/run_extract.sh'], csv_dir);
    end

    C = struct();
    C.types = {'pyr', 'pvalb', 'sst', 'vip'};

    % Numeric 4x4 block of a labeled CSV (row 1 = header, col A = pre-type label).
    read4 = @(name) readmatrix(fullfile(csv_dir, [name '.csv']), 'Range', 'B2:E5');

    % Connectivity (no separate _n; n_probed / n_connected ARE the counts).
    for f = {'conn_prob', 'conn_prob_adj', 'n_probed', 'n_connected'}
        C.(f{1}) = read4(f{1});
    end

    % Per-connection metrics, each with a matching __n sample-count matrix.
    metrics = {'psp_amplitude', 'pulse_amp_90pct', ...
               'stp_induction_50hz', 'stp_recovery_250ms', 'variability_resting', ...
               'ml_facilitation_amount', 'ml_facilitation_tau', ...
               'ml_depression_amount', 'ml_depression_tau', 'ml_release_prob', ...
               'ml_n_release_sites', 'ml_mini_amplitude', ...
               'latency', 'psc_rise_time', 'psc_decay_tau'};
    for k = 1:numel(metrics)
        m = metrics{k};
        C.(m)          = read4(m);
        C.([m '_n'])   = read4([m '__n']);
    end

    % Intrinsic per-type (single-cell) properties, incl. SFA. Each is 4x1 by type,
    % with a matching _n. SI units: tau [s], rheobase [A], input_resistance [Ohm],
    % fi_slope [Hz/A]; adaptation_index / isi_adapt_ratio dimensionless.
    T = readtable(fullfile(this_dir, 'campagnola', 'intrinsic_per_type.csv'), ...
        'VariableNamingRule', 'preserve');
    C.sfa_adaptation_index   = T.adaptation_index;          % 4x1 (historical field name)
    C.sfa_adaptation_index_n = T.adaptation_index_n;
    for p = {'isi_adapt_ratio', 'tau', 'fi_slope', 'rheobase', 'input_resistance'}
        C.(p{1})        = T.(p{1});
        C.([p{1} '_n']) = T.([p{1} '_n']);
    end

    % SFA time constant fit from the raw long-square sweeps (fit_sfa_tau.py), 4x1 [s]
    % aligned to C.types. Missing file -> NaN (the model falls back to its scalar tau_a).
    C.sfa_tau = nan(numel(C.types), 1);
    tau_file = fullfile(this_dir, 'campagnola', 'sfa_tau_per_type.csv');
    if isfile(tau_file)
        Tt = readtable(tau_file, 'VariableNamingRule', 'preserve');
        for i = 1:numel(C.types)
            row = strcmpi(Tt.type, C.types{i});
            if any(row), C.sfa_tau(i) = Tt.tau_a_median_s(find(row, 1)); end
        end
    else
        warning('load_campagnola_matrices:noSfaTau', ...
            'sfa_tau_per_type.csv not found; C.sfa_tau = NaN (model uses scalar tau_a).');
    end
end
